# Project info
version=2.0.0
group=xyz.rose.gateway

# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache = true

# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching = true

# Syncing Gradle is memory hungry with all the subprojects' dependencies
org.gradle.jvmargs=-Xmx4G
