[versions]
# Dependencies
# https://kotlinlang.org/
kotlin = "2.4.10"
# https://insert-koin.io/docs/support/releases/
koin = "4.2.1"
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.11.0"
# https://github.com/Kotlin/kotlinx-datetime
kotlinx-datetime = "0.8.0"
# https://github.com/him188/yamlkt
yamlkt = "0.13.0"
# https://github.com/oshai/kotlin-logging
kotlinLogging = "8.0.4"

# Test Dependencies
# https://mockk.io
mockk = "1.14.11"

# Build tools
# https://github.com/GradleUp/shadow
shadow = "9.6.1"

# Code analysis
# https://github.com/Kotlin/kotlinx-kover
kover = "0.9.9"
# https://detekt.dev/
detekt = "2.0.0-alpha.6"
# https://www.jetbrains.com/help/qodana/quick-start.html#quickstart-gradle-plugin
qodana = "2026.2.0"

# Release tools
# https://github.com/JetBrains/gradle-changelog-plugin
changelog = "2.5.0"

[libraries]
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test", version = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version = "koin" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

yamlkt = { group = "net.mamoe.yamlkt", name = "yamlkt", version.ref = "yamlkt" }
kotlinLogging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlinLogging" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

detekt-junit = { group = "dev.detekt", name = "detekt-test-junit", version.ref = "detekt" }
detekt-ktlint = { group = "dev.detekt", name = "detekt-rules-ktlint-wrapper", version.ref = "detekt" }

plugin-kotlin-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
plugin-shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
#plugin-dotenv = { group = "io.github.klahap.dotenv", name = "dotenv", version.ref = "dotenv" }
plugin-kover = { group = "org.jetbrains.kotlinx", name = "kover-gradle-plugin", version.ref = "kover" }
plugin-detekt = { group = "dev.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
plugin-qodana = { group = "org.jetbrains.qodana", name = "plugin", version.ref = "qodana" }
#plugin-changelog = { group = "org.jetbrains.changelog", name = "org.jetbrains.changelog.gradle.plugin", version.ref = "changelog" }

[plugins]
#kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
#kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
#dotenv = { id = "io.github.klahap.dotenv", version.ref = "dotenv" }
#kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
#detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
#qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }

[bundles]
koin-test = ["koin-test", "koin-test-junit5"]
kotlinx = ["kotlinx-coroutines-core", "kotlinx-datetime"]
