[versions]
# Build tools
# https://docs.papermc.io/paper/dev/project-setup
paper-api = "1.21.7-R0.1-SNAPSHOT"

# Testing tools
# https://github.com/jpenilla/run-paper
run-paper = "2.3.1"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
