[versions]
# Dependencies
# https://github.com/sksamuel/hoplite
hoplite = "2.9.0"
# https://github.com/charleskorn/kaml
kaml = "0.67.0"
# https://tegral.zoroark.guru/docs/modules/core/niwen/
tegral = "0.0.4"

[libraries]
hoplite-core = { group = "com.sksamuel.hoplite", name = "hoplite-core", version.ref = "hoplite" }
hoplite-yaml = { group = "com.sksamuel.hoplite", name = "hoplite-yaml", version.ref = "hoplite" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
tegral = { group = "guru.zoroark.tegral", name = "tegral-niwen-lexer", version.ref = "tegral" }

[bundles]
hoplite = ["hoplite-core", "hoplite-yaml"]
