[versions]
# Dependencies
# https://github.com/sksamuel/hoplite
hoplite = "2.9.0"
# https://github.com/charleskorn/kaml
kaml = "0.77.0"
# https://tegral.zoroark.guru/docs/modules/core/niwen/
tegral = "0.0.4"
# https://insert-koin.io/
koin = "3.5.3"
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.8.0"
# https://github.com/Kotlin/kotlinx-datetime
kotlinx-datetime = "0.5.0"

[libraries]
hoplite-core = { group = "com.sksamuel.hoplite", name = "hoplite-core", version.ref = "hoplite" }
hoplite-yaml = { group = "com.sksamuel.hoplite", name = "hoplite-yaml", version.ref = "hoplite" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
tegral = { group = "guru.zoroark.tegral", name = "tegral-niwen-lexer", version.ref = "tegral" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

[bundles]
hoplite = ["hoplite-core", "hoplite-yaml"]
koin = ["koin-core", "koin-annotations"]
kotlinx = ["kotlinx-coroutines-core", "kotlinx-datetime"]
