[versions]
# Minecraft dependencies
# https://fabricmc.net/develop/
# https://www.minecraft.net/en-us/articles
minecraft = "1.21.4"
# https://github.com/FabricMC/yarn
fabric-yarn = "1.21.4+build.2"
# https://github.com/FabricMC/fabric-loader
fabric-loader = "0.16.9"
# https://github.com/FabricMC/fabric
fabric = "0.112.2+1.21.4"

# Build tools
# https://github.com/FabricMC/fabric-loom
fabric-loom = "1.9-SNAPSHOT"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-yarn = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric" }

[bundles]
fabric = ["fabric", "fabric-loader"]

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
