name: Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - stable
    paths:
      - '**/gradle.properties'


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v7
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      # https://github.com/marketplace/actions/build-with-gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Get release version
        run: |
          VERSION=$(sed -n 's/^version=//p' gradle.properties)
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          [[ $VERSION == *-* ]] && echo "RELEASE_VERSION_PRERELEASE=true" >> $GITHUB_ENV || true
      - name: Build artifacts
        run: ./gradlew shadowJar
      - name: Get changelog
        run: ./gradlew getChangelog --console=plain -q --no-header --no-summary > LATEST_CHANGES.md
      # https://github.com/marketplace/actions/create-release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: Gateway ${{ env.RELEASE_VERSION }}
          tag: v${{ env.RELEASE_VERSION }}
          bodyFile: 'LATEST_CHANGES.md'
          artifacts: 'build/libs/*.jar'
          prerelease: ${{ !!env.RELEASE_VERSION_PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}
