name: Check Pull Request

on:
  pull_request:
    branches:
      - stable
      - dev

    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      # https://github.com/marketplace/actions/build-with-gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build artifacts
        run: ./gradlew shadowJar

  detekt:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      # https://github.com/marketplace/actions/build-with-gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Detekt
        run: ./gradlew detekt
