name: Check Pull Request

on:
  pull_request:
    branches:
      - stable
      - dev

    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin

      # https://github.com/marketplace/actions/build-with-gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build artifacts
        run: ./gradlew shadowJar

  detekt:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin

      # https://github.com/marketplace/actions/build-with-gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Detekt
        run: ./gradlew detekt

  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2026.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          # When pr-mode is set to true, Qodana analyzes only the files that have been changed
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
          upload-result: false
          # quick-fixes available in Ultimate and Ultimate Plus plans
          push-fixes: 'none'
