name: Check Pull Request

on:
  push:
    branches:
      - stable
      - dev
    paths:
      - '**/*.kt'
      - '**/*.kts'
  pull_request:
    branches:
      - stable
      - dev
    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v7
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      # https://github.com/marketplace/actions/build-with-gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/matchers/kotlin.json"
      - name: Build artifacts
        run: ./gradlew shadowJar

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/matchers/junit.json"
      - name: Run tests
        run: ./gradlew test

  detekt:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/matchers/detekt.json"
      - name: Run Detekt
        run: ./gradlew detekt

  qodana:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.draft == false

    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v7
      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/matchers/qodana.json"
      # https://github.com/marketplace/actions/qodana-scan
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2026.2.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          # When pr-mode is set to true, Qodana analyzes only the files that have been changed
          pr-mode: true
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
          upload-result: false
          # quick-fixes available in Ultimate and Ultimate Plus plans
          push-fixes: 'none'
